### ISSUE TITLE
tests hang on Windows

### ISSUE THREAD

**Issue by chorny** [hoelzro/plack-test-anyevent#3]
Tests of your module hang on Windows.
I can provide more verbose information if necessary. If your module cannot work on Windows at all, you can die in Makefile.PL/Build.PL. See http://wiki.cpantesters.org/wiki/CPANAuthorNotes for how to do this.

**Comment by paultcochrane** [comment]
I've been able to reproduce this issue on Windows 7.  As @chorny says, the problem occurs in the `test_infinite_app` test at the call to [`$res->recv;`](https://github.com/hoelzro/plack-test-anyevent/blob/master/t/lib/Plack/Test/AnyEvent/Test.pm#L189).  This leads to [a `recv` call on an AnyEvent object](https://github.com/hoelzro/plack-test-anyevent/blob/master/lib/Plack/Test/AnyEvent/Response.pm#L30), which seems to then go into an infinite loop.  Namely, the code seems to spend a lot of time in the [cb sub inside the call to `AnyEvent->timer` in `test_infinite_app`](https://github.com/hoelzro/plack-test-anyevent/blob/master/t/lib/Plack/Test/AnyEvent/Test.pm#L160).  After letting the process continue, the Perl process then used a full CPU and didn't seem to get any further.  It's possible that AnyEvent is in a never ending wait loop.  If one leaves the Perl process to run long enough, then the CPU usage drops to zero and the process just hangs.  An obvious solution to the problem unfortunately doesn't present itself.  However, perhaps this gives @hoelzro more of a hint as to what the problem potentially is.

**Comment by hoelzro** [comment]
@paultcochrane Thanks for digging in!  I'll try to take a look at this soon

**Comment by hoelzro** [comment]
Thanks again for the Appveyor config @paultcochrane - I signed up for Appveyor last night and it reproduces the issue.  Now it's just a matter of _fixing_ it 😅

**Comment by hoelzro** [comment]
TIL `portable_pipe` is a thing in `AnyEvent::Util` - thanks @paultcochrane for giving me the kick in the pants to work on this!

**Comment by hoelzro** [comment]
@paultcochrane BTW, do you think you'll have more PRs for me over the next few days, or should I cut a release with this fix in it?

**Comment by paultcochrane** [comment]
@hoelzro I think that's all for the time being.  If I spot something before the end of the month, I'll submit further PRs, however if you want to, release away!  :-)
